### ISSUE TITLE
error UnsatisfiedLinkError

### ISSUE THREAD

**Issue by rbj18** [nero520/km-rfid#1]
Hello, I am using the connection example but it gives me the following error.

Exception in thread "main" java.lang.UnsatisfiedLinkError: UHF.Reader18.OpenNetPort(IILjava/lang/String;)[I
	at UHF.Reader18.OpenNetPort(Native Method)
	at UHF.Reader18Manager.init(Reader18Manager.java:50)
	at UHF.Reader18Manager.<init>(Reader18Manager.java:39)
	at UHF.Reader18Manager.<init>(Reader18Manager.java:38)
	at UHF.Reader18Manager$SingletonHolder.<clinit>(Reader18Manager.java:35)
	at UHF.Reader18Manager.getInstance(Reader18Manager.java:31)
	at UHF.Reader18Manager.main(Reader18Manager.java:80)

In the line comResult = reader.OpenNetPort(0xFF,Integer.valueOf(getPort()),getIp());

I put the port and ip correctly but doesn't work. With demo software provided by manufacturer (in c#) works but using the java sdk doesn't work. 

Can you help me, please?

thanks.

**Comment by MrGuo-yan** [comment]
How did you solve it?

**Comment by shrikrushnawagh911** [comment]
How Did you solved it sir/madam?
